name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Run unit tests
      - name: Run tests with Maven
        run: mvn test

      # Build the Docker image (locally)
      - name: Build Docker image
        run: |
          docker build -t file-encryption-utility:${{ github.sha }} .

      # Optionally, run the Docker container (this can be skipped if not needed)
      - name: Run Docker container
        run: |
          docker run -d --name file-encryption-utility-container file-encryption-utility:${{ github.sha }}
